import os
import sys
import argparse
import socket
from urllib.parse import urlparse
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError

def is_anti_bot(title_text: str, content_text: str) -> bool:
    t_lower = title_text.lower()
    c_lower = content_text.lower()
    if "just a moment" in t_lower or "attention required" in t_lower or "security check" in t_lower:
        return True
    if "cf-browser-verification" in c_lower or "challenge-platform" in c_lower or "incapsula" in c_lower or "sucuri_cloudproxy" in c_lower or "akamai bot manager" in c_lower:
        return True
    return False

def is_cdn_error(title_text: str, content_text: str) -> bool:
    t_lower = title_text.lower()
    c_lower = content_text.lower()
    cdn_signatures = [
        "error: the request could not be satisfied",
        "generated by cloudfront",
        "request blocked",
        "reference #",
        "access denied",
        "403 forbidden",
        "403 error",
        "503 service unavailable",
        "edge error",
        "cdn error",
        "imperva"
    ]
    for sig in cdn_signatures:
        if sig in t_lower or sig in c_lower:
            return True
    return False

def check_dns(url: str):
    parsed = urlparse(url)
    hostname = parsed.hostname
    try:
        ip = socket.gethostbyname(hostname)
        print(f"[DNS] Resolved {hostname} to {ip}")
    except Exception as e:
        print(f"[DNS] Failed to resolve {hostname}: {e}")

def debug_site(url: str):
    print(f"==================================================")
    print(f"DEBUGGING SITE: {url}")
    print(f"==================================================")
    
    check_dns(url)
    
    console_messages = []
    network_failures = []
    
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            java_script_enabled=True,
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
            viewport={"width": 1920, "height": 1080},
            locale="en-US",
            timezone_id="America/New_York",
            color_scheme="light",
            extra_http_headers={
                "Accept-Language": "en-US,en;q=0.9",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
                "Upgrade-Insecure-Requests": "1"
            }
        )
        context.add_init_script("""
            Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
            window.navigator.chrome = { runtime: {} };
            Object.defineProperty(navigator, 'plugins', { get: () => [1, 2, 3] });
            Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en'] });
        """)
        
        page = context.new_page()
        
        # Track console errors
        page.on("console", lambda msg: console_messages.append(msg.text) if msg.type == "error" else None)
        
        # Track network failures
        page.on("requestfailed", lambda req: network_failures.append(f"{req.url} ({req.failure})"))
        
        http_status = None
        redirect_chain = []
        
        page.on("response", lambda response: redirect_chain.append(f"{response.status} {response.url}") if response.request.is_navigation_request() else None)
        
        try:
            print("\n[PLAYWRIGHT] Navigating...")
            response = page.goto(url, wait_until="networkidle", timeout=15000)
            
            if response:
                http_status = response.status
                print(f"[HTTP STATUS] {http_status}")
            
            print(f"[FINAL URL] {page.url}")
            
            title = page.title()
            print(f"[PAGE TITLE] {title}")
            
            content = page.content()
            print(f"\n[HTML (First 500 chars)]")
            print(content[:500])
            print("...\n")
            
            is_bot = is_anti_bot(title, content)
            is_cdn = is_cdn_error(title, content)
            
            print(f"[BOT DETECTION RESULT] {'DETECTED' if is_bot else 'Clean'}")
            print(f"[CDN DETECTION RESULT] {'DETECTED' if is_cdn else 'Clean'}")
            
            os.makedirs("reports/debug", exist_ok=True)
            domain = urlparse(url).hostname or "unknown"
            screenshot_path = f"reports/debug/{domain}.png"
            page.screenshot(path=screenshot_path)
            print(f"[SCREENSHOT] Saved to {screenshot_path}")
            
        except PlaywrightTimeoutError as e:
            print(f"[PLAYWRIGHT EXCEPTION] TimeoutError: {e}")
        except Exception as e:
            print(f"[PLAYWRIGHT EXCEPTION] Exception: {e}")
        
        print("\n[REDIRECT CHAIN]")
        for r in redirect_chain:
            print(f"  -> {r}")
            
        print("\n[CONSOLE ERRORS]")
        for err in console_messages[:10]: # Print up to 10
            print(f"  - {err}")
            
        print("\n[NETWORK FAILURES]")
        for nf in network_failures[:10]: # Print up to 10
            print(f"  - {nf}")
            
        browser.close()
        print("\nDone.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("url", help="URL to debug")
    args = parser.parse_args()
    debug_site(args.url)
