"""Feedforward Neural Network training module for IEEE phishing detection.

The module consumes the completed preprocessing CSV and the automatically
selected Top 14 feature names.  It intentionally does not rerun preprocessing,
feature selection, scaling, inference, or any web/API functionality.
"""

from __future__ import annotations

import os
import pickle
import random
import time
from datetime import datetime
from io import StringIO
from pathlib import Path
from typing import Any

# Suppress TensorFlow's verbose startup messages before importing it.
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import (
    accuracy_score,
    auc,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split


_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_DATA_PATH = _PROJECT_ROOT / "data" / "dataset_small_preprocessed.csv"
_SELECTED_FEATURES_PATH = _PROJECT_ROOT / "models" / "top14_features.pkl"
_MODELS_DIR = _PROJECT_ROOT / "models"
_REPORTS_DIR = _PROJECT_ROOT / "reports"
_TARGET_COLUMN = "phishing"
_RANDOM_STATE = 42

_MODEL_PATH = _MODELS_DIR / "fnn_model.keras"
_HISTORY_PATH = _MODELS_DIR / "training_history.pkl"


def load_training_data(
    data_path: Path = _DATA_PATH,
    selected_features_path: Path = _SELECTED_FEATURES_PATH,
) -> tuple[pd.DataFrame, pd.Series, list[str]]:
    """Load the processed CSV and select only persisted Top 14 input features."""
    if not data_path.exists():
        raise FileNotFoundError(f"Processed dataset not found: {data_path}")
    if not selected_features_path.exists():
        raise FileNotFoundError(f"Selected feature list not found: {selected_features_path}")

    # The CSV already contains MinMax-scaled values; read it without changing
    # values, then use the feature order generated by feature selection.
    dataframe = pd.read_csv(data_path)
    with selected_features_path.open("rb") as file:
        selected_features = pickle.load(file)

    if _TARGET_COLUMN not in dataframe.columns:
        raise ValueError(f"Target column '{_TARGET_COLUMN}' is missing from the dataset.")
    if not isinstance(selected_features, list) or not selected_features:
        raise ValueError("top14_features.pkl must contain a non-empty ordered list.")

    missing_features = [feature for feature in selected_features if feature not in dataframe.columns]
    if missing_features:
        raise ValueError(f"Selected features missing from dataset: {missing_features}")

    features = dataframe.loc[:, selected_features].astype(np.float32)
    target = dataframe[_TARGET_COLUMN].astype(np.int32)
    if target.nunique() != 2:
        raise ValueError("Binary FNN training requires exactly two target classes.")

    print(f"Dataset loaded: {dataframe.shape[0]:,} rows, {features.shape[1]} selected features.")
    return features, target, selected_features


def build_model(input_dimension: int) -> tf.keras.Model:
    """Build the requested 64-32-1 ReLU/Dropout/Sigmoid FNN architecture."""
    if input_dimension <= 0:
        raise ValueError("Model input dimension must be positive.")

    # The Input layer fixes the schema to the dynamically loaded Top 14 list.
    model = tf.keras.Sequential(
        [
            tf.keras.layers.Input(shape=(input_dimension,), name="selected_features"),
            tf.keras.layers.Dense(64, activation="relu", name="dense_64"),
            tf.keras.layers.Dropout(0.30, name="dropout_64"),
            tf.keras.layers.Dense(32, activation="relu", name="dense_32"),
            tf.keras.layers.Dropout(0.30, name="dropout_32"),
            tf.keras.layers.Dense(1, activation="sigmoid", name="phishing_probability"),
        ],
        name="ieee_phishing_fnn",
    )
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss=tf.keras.losses.BinaryCrossentropy(),
        metrics=[
            tf.keras.metrics.BinaryAccuracy(name="accuracy"),
            tf.keras.metrics.Precision(name="precision"),
            tf.keras.metrics.Recall(name="recall"),
            tf.keras.metrics.AUC(name="auc"),
        ],
    )
    return model


def train_model(
    model: tf.keras.Model,
    x_train: pd.DataFrame,
    y_train: pd.Series,
    x_validation: pd.DataFrame,
    y_validation: pd.Series,
) -> tuple[tf.keras.callbacks.History, float, bool]:
    """Train once with the specified epochs, batch size, and EarlyStopping."""
    early_stopping = tf.keras.callbacks.EarlyStopping(
        monitor="val_loss", patience=5, restore_best_weights=True
    )
    start_time = time.perf_counter()

    # Validation data is the reproducible held-out 20% split; no further split
    # is made, preventing accidental loss of validation sample traceability.
    history = model.fit(
        x_train,
        y_train,
        validation_data=(x_validation, y_validation),
        epochs=40,
        batch_size=32,
        callbacks=[early_stopping],
        verbose=2,
    )
    elapsed_seconds = time.perf_counter() - start_time
    early_stopped = len(history.history["loss"]) < 40
    return history, elapsed_seconds, early_stopped


def evaluate_model(
    model: tf.keras.Model,
    x_validation: pd.DataFrame,
    y_validation: pd.Series,
) -> dict[str, Any]:
    """Calculate all requested validation metrics from sigmoid probabilities."""
    probabilities = model.predict(x_validation, verbose=0).ravel()
    predictions = (probabilities >= 0.5).astype(np.int32)
    y_true = y_validation.to_numpy()

    return {
        "accuracy": float(accuracy_score(y_true, predictions)),
        "precision": float(precision_score(y_true, predictions, zero_division=0)),
        "recall": float(recall_score(y_true, predictions, zero_division=0)),
        "f1_score": float(f1_score(y_true, predictions, zero_division=0)),
        "roc_auc": float(auc(*roc_curve(y_true, probabilities)[:2])),
        "confusion_matrix": confusion_matrix(y_true, predictions),
        "classification_report": classification_report(
            y_true, predictions, target_names=["legitimate", "phishing"], zero_division=0
        ),
        "probabilities": probabilities,
        "y_true": y_true,
    }


def save_model(model: tf.keras.Model, history: tf.keras.callbacks.History) -> None:
    """Save the trained Keras model and serializable training-history dictionary."""
    _MODELS_DIR.mkdir(parents=True, exist_ok=True)
    model.save(_MODEL_PATH)
    with _HISTORY_PATH.open("wb") as file:
        pickle.dump(history.history, file, protocol=pickle.HIGHEST_PROTOCOL)
    print(f"Model saved: {_MODEL_PATH}")
    print(f"Training history saved: {_HISTORY_PATH}")


def _save_learning_curves(history: dict[str, list[float]]) -> None:
    """Generate accuracy and loss learning curves from the saved Keras history."""
    epochs = range(1, len(history["loss"]) + 1)
    for metric, validation_metric, title, y_label, output_name in [
        ("accuracy", "val_accuracy", "Training and Validation Accuracy", "Accuracy", "training_accuracy.png"),
        ("loss", "val_loss", "Training and Validation Loss", "Binary crossentropy loss", "training_loss.png"),
    ]:
        figure, axis = plt.subplots(figsize=(8, 5))
        axis.plot(epochs, history[metric], label="Training")
        axis.plot(epochs, history[validation_metric], label="Validation")
        axis.set(title=title, xlabel="Epoch", ylabel=y_label)
        axis.legend()
        axis.grid(alpha=0.25)
        figure.tight_layout()
        figure.savefig(_REPORTS_DIR / output_name, dpi=200)
        plt.close(figure)


def _save_confusion_matrix(matrix: np.ndarray) -> None:
    """Render the requested labelled validation confusion-matrix plot."""
    figure, axis = plt.subplots(figsize=(6, 5))
    image = axis.imshow(matrix, interpolation="nearest", cmap="Blues")
    figure.colorbar(image, ax=axis)
    labels = ["Legitimate", "Phishing"]
    axis.set(xticks=[0, 1], yticks=[0, 1], xticklabels=labels, yticklabels=labels,
             xlabel="Predicted label", ylabel="True label", title="FNN Confusion Matrix")
    threshold = matrix.max() / 2 if matrix.size else 0
    for row in range(matrix.shape[0]):
        for column in range(matrix.shape[1]):
            axis.text(column, row, str(matrix[row, column]), ha="center", va="center",
                      color="white" if matrix[row, column] > threshold else "black")
    figure.tight_layout()
    figure.savefig(_REPORTS_DIR / "confusion_matrix.png", dpi=200)
    plt.close(figure)


def _save_roc_curve(y_true: np.ndarray, probabilities: np.ndarray, roc_auc: float) -> None:
    """Render ROC curve from validation probabilities and report its AUC."""
    false_positive_rate, true_positive_rate, _ = roc_curve(y_true, probabilities)
    figure, axis = plt.subplots(figsize=(7, 5))
    axis.plot(false_positive_rate, true_positive_rate, label=f"FNN (AUC = {roc_auc:.4f})")
    axis.plot([0, 1], [0, 1], "--", color="grey", label="Chance")
    axis.set(xlabel="False Positive Rate", ylabel="True Positive Rate", title="FNN ROC Curve")
    axis.legend(loc="lower right")
    axis.grid(alpha=0.25)
    figure.tight_layout()
    figure.savefig(_REPORTS_DIR / "roc_curve.png", dpi=200)
    plt.close(figure)


def generate_reports(
    model: tf.keras.Model,
    history: tf.keras.callbacks.History,
    metrics: dict[str, Any],
    dataset_size: int,
    training_samples: int,
    validation_samples: int,
    selected_features: list[str],
    training_seconds: float,
    early_stopped: bool,
) -> None:
    """Create every requested text and visual training artifact."""
    _REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    _save_learning_curves(history.history)
    _save_confusion_matrix(metrics["confusion_matrix"])
    _save_roc_curve(metrics["y_true"], metrics["probabilities"], metrics["roc_auc"])

    summary_buffer = StringIO()
    model.summary(print_fn=lambda line: summary_buffer.write(line + "\n"))
    architecture = summary_buffer.getvalue()
    (_REPORTS_DIR / "model_summary.txt").write_text(architecture, encoding="utf-8")
    (_REPORTS_DIR / "classification_report.txt").write_text(
        metrics["classification_report"], encoding="utf-8"
    )

    matrix = metrics["confusion_matrix"]
    report = f"""{'=' * 72}
IEEE PHISHING DETECTION PROJECT - FNN TRAINING REPORT
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
{'=' * 72}

DATASET AND SPLIT
{'-' * 72}
Dataset size: {dataset_size:,} samples
Training samples: {training_samples:,}
Validation samples: {validation_samples:,}
Input features ({len(selected_features)}): {', '.join(selected_features)}
Target column: {_TARGET_COLUMN}
Split: train_test_split(test_size=0.20, stratify=y, random_state=42)

MODEL ARCHITECTURE
{'-' * 72}
{architecture}
Trainable parameters: {model.count_params():,}
Loss: Binary Crossentropy
Optimizer: Adam (learning_rate=0.001)
Metrics: Accuracy, Precision, Recall, AUC
Training configuration: epochs=40, batch_size=32
Early stopping: monitor=val_loss, patience=5, restore_best_weights=True
Early stopping triggered: {early_stopped}
Epochs completed: {len(history.history['loss'])}
Training time: {training_seconds:.2f} seconds

VALIDATION METRICS
{'-' * 72}
Accuracy: {metrics['accuracy']:.6f}
Precision: {metrics['precision']:.6f}
Recall: {metrics['recall']:.6f}
F1 Score: {metrics['f1_score']:.6f}
ROC AUC: {metrics['roc_auc']:.6f}
Confusion matrix:
{matrix}

FINAL CONCLUSION
{'-' * 72}
The FNN was trained once on the automatically selected Top 14 features from
the IEEE phishing dataset. These inputs are the features whose permutation
most affected Random Forest classification, so they provide a compact and
informative representation for the neural network. The saved .keras model,
history, and reports are ready for the next inference-pipeline phase.
"""
    (_REPORTS_DIR / "training_report.txt").write_text(report, encoding="utf-8")
    print("Training reports generated.")


def train_fnn() -> dict[str, Any]:
    """Execute one complete, reproducible FNN train/evaluate/save workflow."""
    # Seed Python, NumPy, and TensorFlow before splitting/building/training.
    random.seed(_RANDOM_STATE)
    np.random.seed(_RANDOM_STATE)
    tf.keras.utils.set_random_seed(_RANDOM_STATE)

    features, target, selected_features = load_training_data()
    x_train, x_validation, y_train, y_validation = train_test_split(
        features, target, test_size=0.20, stratify=target, random_state=_RANDOM_STATE
    )

    model = build_model(input_dimension=len(selected_features))
    print("FNN model built.")
    history, training_seconds, early_stopped = train_model(
        model, x_train, y_train, x_validation, y_validation
    )
    print("Training completed.")

    metrics = evaluate_model(model, x_validation, y_validation)
    save_model(model, history)
    generate_reports(
        model, history, metrics, len(features), len(x_train), len(x_validation),
        selected_features, training_seconds, early_stopped
    )

    # Final verification ensures the exact requested deliverables exist.
    required_artifacts = [_MODEL_PATH, _HISTORY_PATH] + [
        _REPORTS_DIR / name for name in (
            "training_accuracy.png", "training_loss.png", "confusion_matrix.png",
            "roc_curve.png", "classification_report.txt", "model_summary.txt",
            "training_report.txt",
        )
    ]
    if not all(path.exists() for path in required_artifacts):
        missing = [str(path) for path in required_artifacts if not path.exists()]
        raise RuntimeError(f"Training completed but artifacts are missing: {missing}")

    print("\nFeedforward Neural Network Training Module successfully implemented.")
    print(f"Model Accuracy: {metrics['accuracy']:.4f}")
    print(f"Validation Accuracy: {history.history['val_accuracy'][-1]:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1 Score: {metrics['f1_score']:.4f}")
    print(f"ROC-AUC: {metrics['roc_auc']:.4f}")
    print("Artifacts Generated: fnn_model.keras, training_history.pkl, and all reports.")
    return metrics


if __name__ == "__main__":
    train_fnn()
